services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev
    container_name: ${MICROSERVICE_NAME}
    working_dir: /app
    volumes:
      - ./${MICROSERVICE_FOLDER}:/app
      - /app/node_modules
    ports:
      - '${PUBLIC_HTTP_PORT}:3000'
    stdin_open: true
    tty: true
    depends_on:
      - database
  database:
    image: mysql:9.1.0
    container_name: mysql_${MICROSERVICE_NAME}
    ports:
      - ${PUBLIC_MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 3